<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BancoKRT.Application\BancoKRT.Application.csproj" />
    <ProjectReference Include="..\BancoKRT.Infrastructure\BancoKRT.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
	<Folder Include="Properties\" />
	<Folder Include="Contracts\" />
	<Folder Include="Controllers\" />
	<Folder Include="ExceptionHandling\" />
    <Folder Include="Extensions\" />
  </ItemGroup>

</Project>
